networks:
    dev:

services:
    nginx:
        image: nginx:stable-alpine
        ports:
            - "80:80"
        volumes:
            - "./nginx.conf:/etc/nginx/nginx.conf"
        depends_on:
            - backend-mic1
            - backend-mic2
            - frontend
        networks:
            - dev
    backend-mic1:
        build:
            context: ./backendmicroservices/inventory/app
        networks:
            - dev
        ports:
            - "8000:8000"

    backend-mic2:
        build:
            context: ./backendmicroservices/payment/app
        networks:
            - dev
        ports:
            - "8001:8001"

    frontend:
        build:
            context: ./frontend
        networks:
            - dev
        ports:
            - "5173:5173"
