name: Docker CI/CD Pipeline 

on: 
  push:
    branches:
    - main 
  workflow_dispatch:
jobs: 
  build_and_test_docker_image: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
  
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }} 
          
      - name: Build Docker image
        run: docker build -t my-app:latest ./backendmicroservices/inventory/app
  
      - name: Run Docker container
        run: docker run -d -p 8000:8000 --name my-app-container my-app:latest
  
      - name: Wait for the aplication to start 
        run: sleep 10
  
      - name: Test the application with curl 
        run: | 
          if curl -s http://localhost:8000/products; then 
            echo "Application is running successfully."
          else 
            echo "Application did not start correctly"
            exit 1
          fi
  
      - name : Stop and remove Docker container 
        run: docker stop my-app-container && docker rm my-app-container 
  
      - name: Tag Docker image2
        run: docker tag inventoryMic:latest stenty/inventoryMic:latest
  
      - name: Push Docker image to DockerHub
        run: docker push stenty/my-app:latest
  
  
        
  
      
